Add docker building and publishing to ghcr.io with github actions
wtsi-npg/bambi pull request #196
Opened 2023-09-05 20:30 UTC by jmtcsngr

Trying to add container building scaffolding, building and publishing using github actions. Marking as draft because there are some pending things.

- [ ] Do we want a docker/README.md with instructions about how to use the container?
- [ ] Not clear yet what to do with the manifest. I stole things from irods clients but just to get an idea of what to have there. Placeholder kind of thing.
- [ ] Even with some cleaning the container is about 600MB we could try to reduce the thing more
- [ ] Not sure what we want for `CMD` and `ENTRYPOINT`. As it is now I'm assuming we will do something like `docker run ghcr.io/wtsi-npg/bambi bambi`. But we should also support check_bcl. Do we want to have an entrypoint script?
- [ ] Do we want to have things running with an app user inside the container?
- [ ] Do we want to build the container as part of non publishing actions/test (build on all push to branches)? I think it makes things safer because when tagging you are sure the container will build.

The Dockerfile is mostly inspired/stolen from the package instructions.
Linting is not necessary but I like it
The publishing is heavily inspired on [npg-irods-python create-release action](https://github.com/wtsi-npg/npg-irods-python/blob/c489da6f7c2bc8380f8c1ca4eea798c4aecbb5e3/.github/workflows/create-release.yml) 

I have built and published from my fork and it is happy `docker pull ghcr.io/jmtcsngr/bambi` `docker run ghcr.io/jmtcsngr/bambi bambi --version` `docker run ghcr.io/jmtcsngr/bambi check_bcl`

2023-09-06 09:14 UTC, kjsanger commented on docker/Dockerfile
> +      libssl-dev \
Do you need these dev packages to be included in the final image?

2023-09-06 09:54 UTC, jmtcsngr commented
Will drop `manifest.json` and try dropping the `-dev` versions.

2023-09-06 13:48 UTC, jmtcsngr commented
In a weird turn of events the image produced using `bitnami/minideb` was larger than the one produced using `debian:bookworm` as base. So keeping `debian:bookworm` as base.

```
REPOSITORY               TAG       IMAGE ID       CREATED              SIZE
ghcr.io/jmtcsngr/bambi   latest    8420aa0b0c77   About a minute ago   246MB (debian:bookworm)
ghcr.io/jmtcsngr/bambi   <none>    ceeafd97f15c   23 minutes ago       250MB (bitnami/minideb)
```

2023-09-07 08:46 UTC, kjsanger requested changes

2023-09-07 08:46 UTC, kjsanger commented on .github/workflows/docker.yml
> +        uses: actions /checkout@v3
Rogue space before the slash

2023-09-07 08:46 UTC, kjsanger commented on docker/Dockerfile
> +    mkdir -p /tmp/usr/local && autoreconf -i && ./configure --prefix=/tmp/usr/local && make && make install
Minor: split this line after each `&&`

2023-09-07 08:46 UTC, kjsanger commented on .github/workflows/create-release.yml
> +            --label "uk.ac.sanger.commit=$GIT_COMMIT" \
Recent builds use more standard label keys in the `org.opencontainers.image` namespace (the npg-irods-python Dockerfile that you cite doesn't and needs an update). E.g.

https://github.com/wtsi-npg/containers/blob/cf85a218b088e20632f75f8ea902eaf0c4cf2acb/docker/Makefile#L282-L298

2023-09-07 08:46 UTC, kjsanger commented on .github/workflows/docker.yml
> +name: "Docker"
Please can you name this (and the YAML file) with an imperative that describes whta this does (along the lines of `run-tests`, `create-release` that we have elsewhere). Maybe lint-dockerfile? But it also builds an image, presumably as a test? (not uiqte clear to me) so maybe there's a better expression.

2023-09-07 14:36 UTC, jmtcsngr commented on .github/workflows/create-release.yml
> +            --label "uk.ac.sanger.commit=$GIT_COMMIT" \
Does this look good? Still need to test the actual syntax works, but just to know which labels we expect.

```
--label "org.opencontainers.image.title=bambi" \
--label "org.opencontainers.image.source=${GIT_URL}" \
--label "org.opencontainers.image.revision=${GIT_COMMIT}" \
--label "org.opencontainers.image.version=$(shell git describe --always)" \
--label "org.opencontainers.image.created=$(shell date --utc --iso-8601=seconds)" \
```

2023-09-07 14:36 UTC, jmtcsngr commented on .github/workflows/docker.yml
> +name: "Docker"
This is what I meant with:
"Do we want to build the container as part of non publishing actions/test (build on all push to branches)? I think it makes things safer because when tagging you are sure the container will build." In the PR's first comment.

I'm happy with whatever @kjsanger and @dkj want. We could just drop this action if we don't think we need it. An alternative would be to create tags in the fork to check things build. But tagging to trigger a "build + publish" in a fork feels to me like a misuse of tagging.

2023-09-07 15:38 UTC, jmtcsngr commented on .github/workflows/create-release.yml
> +            --label "uk.ac.sanger.commit=$GIT_COMMIT" \
In containers we have the `TAG` as `git describe --always`. Would you prefer that over `git describe --always --tags --dirty`.

2023-09-13 10:17 UTC, kjsanger commented on .github/workflows/create-release.yml
> +            --label "uk.ac.sanger.commit=$GIT_COMMIT" \
bambi calls git in its `autoconf` step to get a version number which the built executable will report with `--version`. The version reported by the container must be identical to whatever that reports.
It's not ideal that this is configured in two places (`configure.ac` and here), so it's worth having a comment about that here, to try to avoid drift.

2023-09-13 10:21 UTC, kjsanger requested changes

2023-09-13 10:21 UTC, kjsanger commented on .github/workflows/lint-and-test-build-dockerfile.yml
> +name: "lint and test-build Dockerfile"
Minor: lint -> Lint

2023-09-13 10:36 UTC, jmtcsngr commented on .github/workflows/create-release.yml
> +            --label "uk.ac.sanger.commit=$GIT_COMMIT" \
Good point about the version. Will add the comment here. Don't think there is an easy way to have everything in one place.

In a related thing, `bambi --version` reports also the htslib version:

```
bambi 0.16.1
Using htslib 1.17
Copyright (C) 2017 Genome Research Ltd.
```

Do we want that (htslib version) anywhere in the labels?

2023-09-13 12:09 UTC, kjsanger commented on .github/workflows/create-release.yml
> +            --label "uk.ac.sanger.commit=$GIT_COMMIT" \
Hmm. I'd say no, mainly because a change of htslib version should result in a new bambi release (also because there isn't a standard attribute for it)

2023-09-13 12:47 UTC, kjsanger approved these changes

2023-09-13 12:49 UTC, merged